### ISSUE TITLE
when scraping over 100+

### ISSUE THREAD

**Issue by ghost** [mishra-ankit/ddg-image-downloader#1]
query: ddg-download -q "TEST" -l 200 -o D:/TEST/ -s Large

    FetchError: invalid json response body at https://duckduckgo.com/i.js?q=TEST&o=json&p=1&s=100&u=bing&f=size
    :Large&l=us-envqd=3-7881987615749384088387219545045329831-138715393788132230994278379252081294656 reason:
    Unexpected token I in JSON at position 0

**Comment by mishra-ankit** [comment]
Thanks a lot for reporting the bug. 
My apologies for super long delay, the bug is fixed now, with some other improvements. 
Though you might not even need the tool anymore.
